---
title: "binning ic50s to score"
author: "Kristi Lin-Rahardja"
date: "2024-03-21"
output: html_document
---


# Load Packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
# devtools::install_github("cancerrxgene/gdscIC50", build_vignettes=FALSE) #restart R after downloading

library(here)
library(patchwork) #for plotting
library(tidyverse)

conflicted::conflict_prefer("here", "here")
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("mutate", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
```

# Load Data

```{r load_signatures}
sig_files = list.files(here("Data", "Signatures"))
sigs = lapply(sig_files, function(x) readRDS(here("Data", "Signatures", x)))
names(sigs) = gsub("\\_.*", "", sig_files) #cut off everything after the first underscore

## we also need the full drug names to match with the correct drug response data. those need to be manually entered in the *same order* as the list shows
#make sure theyre spelled right! can check the `drug_id_key` table for spelling
names(sigs) #print this to make sure the order is correct
sig_drugs = c("Cisplatin", "Cytarabine", "5-Fluorouracil", "Gemcitabine", "Irinotecan",
              "Luminespib", "Paclitaxel", "Topotecan", "Vinblastine", "Vorinostat")

rm(sig_files)
```

```{r load_prepped_data}
cell_lines = readRDS(here("Data", "cleaned_cell_line_meta.rds"))
subtype_key = readRDS(here("Data", "subtype_key.rds"))
drug_id_key = readRDS(here("Data", "drug_id_key.rds"))

fitted_dr = readxl::read_excel(here("Data", "Raw Data", "GDSC2_fitted_dose_response.xlsx")) %>%
  select(COSMIC_ID, DRUG_NAME, LN_IC50, AUC) %>%
  filter(DRUG_NAME %in% sig_drugs) %>%
  mutate(cell_line=as.character(COSMIC_ID))

drug_abbrev_key = data.frame(drug_abbrev=names(sigs), #add drug abbrevs to fitted_dr
                             DRUG_NAME=sig_drugs)
fitted_dr = left_join(fitted_dr, drug_abbrev_key,
                      by="DRUG_NAME")
fitted_dr = left_join(fitted_dr, subtype_key,
                      by="cell_line")
```

```{r load_results}
scores=readRDS(here("Results",
                     paste0(length(sigs), "sig_scores.rds")))

scores = na.omit(scores)

scores_long = pivot_longer(scores,
                           cols = c(names(sigs)),
                           names_to = "drug_abbrev",
                           values_to = "score")

#add ranks
#create a new df to store the rankings in
scores_sup = data.frame(matrix(nrow=0, ncol=(ncol(scores_long)+1)))
colnames(scores_sup) = c(colnames(scores_long), "rank")
#create a vector of all the cell lines to go through
cl_list = unique(scores_long$cell_line)

for(i in 1:length(cl_list)){
  #for each cell line, sort by descending sig score (most to least sensitive)
  temp = scores_long %>% filter(cell_line == cl_list[i])
  temp = temp[order(temp$score, decreasing = TRUE),]
  temp$rank = seq(1:nrow(temp)) #label the ranking from most to least sensitive
  
  scores_sup = rbind(scores_sup, temp) #combine results with the previous iteration
}
rm(temp)

scores_sup = scores_sup %>%
  mutate(rank = factor(rank, ordered=TRUE,
                       levels = seq(1:length(sigs))))
```


# Label nTile

```{r}
drugs = names(sigs)
subtypes = unique(subtype_key$subtype)

#label ntile, where n is # drugs. 1 = most sensitive (low IC50, low AUC)
for(j in 1:length(drugs)){
  for(i in 1:length(subtypes)){
    temp = fitted_dr %>% 
      filter(subtype == subtypes[i] & drug_abbrev == drugs[j])
    if(nrow(temp)>=length(sigs)){
      temp$ntile = ntile(temp$LN_IC50, length(sigs))
    } else {
      temp$ntile = NA
    }
    
    if(j==1 & i==1){
      binned_dr = temp
    } else {
      binned_dr = rbind(binned_dr, temp)
    }
    
  }
}
```

Combine with predicted sensitivity ranking & determine "accuracy" score

```{r}
merged = full_join(scores_sup %>% select(-score),
                   binned_dr%>%select(cell_line, drug_abbrev,
                                      subtype, ntile),
                   by=c("cell_line", "drug_abbrev", "subtype"))
length(unique(merged$cell_line)) #1,046
merged=na.omit(merged) #remove what can't be scored
length(unique(merged$cell_line)) #918, lost 128

#calc the difference between sens rank and bin #
merged = merged %>%
  mutate(rank = as.numeric(rank),
         dif = ntile-rank,
         abs_dif = abs(ntile-rank))
```

calculate "acc" score by averaging the differences per cell line

```{r}
cl_list = unique(merged$cell_line)

for(i in 1:length(cl_list)){
  temp = merged %>% 
    filter(cell_line==cl_list[i])
  av_dif = mean(temp$dif)
  av_abs_dif = mean(temp$abs_dif)
  
  temp_results = data.frame(cell_line=cl_list[i],
                            subtype=unique(temp$subtype),
                            av_dif = av_dif,
                            av_abs_dif = av_abs_dif)
  
  if(i==1){
    results = temp_results
  } else {
    results = rbind(results, temp_results)
  }
}
```

```{r}
saveRDS(merged,
        here("Results", "bin_ic50_ranks.rds"))
saveRDS(results,
        here("Results", "bin_ic50_results.rds"))
```


# Plot Results

```{r}
#create a new df with one row per subtype, and columns = subtype, proportion_correct
subtype_scores = data.frame(subtype=subtypes, av_dif=0, av_abs_dif=0, n = 0)

for (i in 1:length(subtypes)){
    #Subset data per subtype
    subset = results[which(results$subtype == subtypes[i]),]
    
    #Store subtype name
    subtype_scores$subtype[i] = subtypes[i]
    
    #calc and store % of cell line survivals correctly predicted
    subtype_scores$av_dif[i] = mean(subset$av_dif)
    subtype_scores$av_abs_dif[i] = mean(subset$av_abs_dif)
    
    #Indicate number of cell lines in subtype (n)
    subtype_scores$n[i] = nrow(subset)
}

subtype_scores = na.omit(subtype_scores)

#order the rows by highest to lowest correct
subtype_scores = subtype_scores[order(subtype_scores$av_dif),]

#To maintain this order when we plot later, factorize the column
subtype_scores$subtype <- factor(subtype_scores$subtype,
                                      ordered = TRUE,
                                      levels = subtype_scores$subtype)
cancer_order = (as.character(subtype_scores$subtype))

results$subtype <- factor(results$subtype,
                          ordered = TRUE,
                          levels = c(cancer_order))
```

```{r}
#av_dif tells us about whether the sigs tend to over or under predict sensitivity
#ntile-rank, rank tends to be higher than ntile which means sigs tend to predict things are more resistant than they actually are
ggplot(results, aes(x=subtype, y=av_dif)) + 
  geom_violin() +
  geom_boxplot(width=0.1)


#av_abs_dif is more informative about the overall performance
#want this to be as close to 0 as possible
#hard to judge how "acceptable" these results are until we compare to a null dist
ggplot(results, aes(x=subtype, y=av_abs_dif)) + 
  geom_violin() +
  geom_boxplot(width=0.1)
```

should be able to load null data from the same run as before, just change the way we score the null predictions

```{r}
null_1000_bootstrap_10sig_indiv_scores <- readRDS("~/PhD/Projects/evol-chemogram/Results/null_1000_bootstrap_10sig_indiv_scores.rds")
```

